# Generated by Django 2.2.14 on 2020-08-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Post',
        ),
    ]
